# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/bip44_page.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 374)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(300, 10, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setGeometry(QtCore.QRect(630, 330, 81, 27))
        self.close_btn.setObjectName("close_btn")
        self.coin_add_btn = QtWidgets.QPushButton(Dialog)
        self.coin_add_btn.setGeometry(QtCore.QRect(110, 270, 41, 27))
        self.coin_add_btn.setObjectName("coin_add_btn")
        self.coin_rm_btn = QtWidgets.QPushButton(Dialog)
        self.coin_rm_btn.setGeometry(QtCore.QRect(110, 300, 71, 27))
        self.coin_rm_btn.setObjectName("coin_rm_btn")
        self.acc_rm_btn = QtWidgets.QPushButton(Dialog)
        self.acc_rm_btn.setGeometry(QtCore.QRect(190, 300, 71, 27))
        self.acc_rm_btn.setObjectName("acc_rm_btn")
        self.addr_rm_btn = QtWidgets.QPushButton(Dialog)
        self.addr_rm_btn.setGeometry(QtCore.QRect(300, 300, 71, 27))
        self.addr_rm_btn.setObjectName("addr_rm_btn")
        self.acc_add_btn = QtWidgets.QPushButton(Dialog)
        self.acc_add_btn.setGeometry(QtCore.QRect(190, 270, 41, 27))
        self.acc_add_btn.setObjectName("acc_add_btn")
        self.addr_add_btn = QtWidgets.QPushButton(Dialog)
        self.addr_add_btn.setGeometry(QtCore.QRect(300, 270, 41, 27))
        self.addr_add_btn.setObjectName("addr_add_btn")
        self.coin_list = QtWidgets.QListWidget(Dialog)
        self.coin_list.setGeometry(QtCore.QRect(110, 30, 71, 241))
        self.coin_list.setObjectName("coin_list")
        self.acc_list = QtWidgets.QListWidget(Dialog)
        self.acc_list.setGeometry(QtCore.QRect(190, 30, 101, 241))
        self.acc_list.setObjectName("acc_list")
        self.addr_list = QtWidgets.QListWidget(Dialog)
        self.addr_list.setGeometry(QtCore.QRect(300, 30, 321, 241))
        self.addr_list.setObjectName("addr_list")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mk_rm_btn = QtWidgets.QPushButton(Dialog)
        self.mk_rm_btn.setGeometry(QtCore.QRect(10, 300, 71, 27))
        self.mk_rm_btn.setObjectName("mk_rm_btn")
        self.mk_list = QtWidgets.QListWidget(Dialog)
        self.mk_list.setGeometry(QtCore.QRect(10, 30, 91, 241))
        self.mk_list.setObjectName("mk_list")
        self.mk_add_btn = QtWidgets.QPushButton(Dialog)
        self.mk_add_btn.setGeometry(QtCore.QRect(10, 270, 41, 27))
        self.mk_add_btn.setObjectName("mk_add_btn")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(630, 30, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(630, 60, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Coin"))
        self.label_2.setText(_translate("Dialog", "Account"))
        self.label_4.setText(_translate("Dialog", "Address"))
        self.close_btn.setText(_translate("Dialog", "Close"))
        self.coin_add_btn.setText(_translate("Dialog", "Add"))
        self.coin_rm_btn.setText(_translate("Dialog", "Remove"))
        self.acc_rm_btn.setText(_translate("Dialog", "Remove"))
        self.addr_rm_btn.setText(_translate("Dialog", "Remove"))
        self.acc_add_btn.setText(_translate("Dialog", "Add"))
        self.addr_add_btn.setText(_translate("Dialog", "Add"))
        self.label_5.setText(_translate("Dialog", "Master Key"))
        self.mk_rm_btn.setText(_translate("Dialog", "Remove"))
        self.mk_add_btn.setText(_translate("Dialog", "Add"))
        self.label_6.setText(_translate("Dialog", "Balance"))
        self.label_7.setText(_translate("Dialog", "1.0 BTC"))

