all: bip44_page.py rcv_page.py send_page.py chain_creation.py coin_selection.py account_creation.py

bip44_page.py : ui/bip44_page.ui
	pyuic5 ui/bip44_page.ui -o bip44_page.py
rcv_page.py : ui/rcv_page.ui
	pyuic5 ui/rcv_page.ui -o rcv_page.py
send_page.py : ui/send_page.ui
	pyuic5 ui/send_page.ui -o send_page.py
chain_creation.py : ui/chain_creation.ui
	pyuic5 ui/chain_creation.ui -o chain_creation.py
coin_selection.py : ui/coin_selection.ui
	pyuic5 ui/coin_selection.ui -o coin_selection.py
account_creation.py : ui/account_creation.ui
	pyuic5 ui/account_creation.ui -o account_creation.py
