# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/send_page.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.balance_label = QtWidgets.QLabel(Dialog)
        self.balance_label.setGeometry(QtCore.QRect(300, 20, 66, 17))
        self.balance_label.setObjectName("balance_label")
        self.fee_label = QtWidgets.QLabel(Dialog)
        self.fee_label.setGeometry(QtCore.QRect(60, 220, 66, 17))
        self.fee_label.setObjectName("fee_label")
        self.amount_label = QtWidgets.QLabel(Dialog)
        self.amount_label.setGeometry(QtCore.QRect(50, 166, 66, 31))
        self.amount_label.setObjectName("amount_label")
        self.total_label = QtWidgets.QLabel(Dialog)
        self.total_label.setGeometry(QtCore.QRect(60, 260, 66, 17))
        self.total_label.setObjectName("total_label")
        self.address_label = QtWidgets.QLabel(Dialog)
        self.address_label.setGeometry(QtCore.QRect(10, 80, 66, 20))
        self.address_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.address_label.setObjectName("address_label")
        self.note_label = QtWidgets.QLabel(Dialog)
        self.note_label.setGeometry(QtCore.QRect(10, 110, 66, 21))
        self.note_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.note_label.setObjectName("note_label")
        self.postbalance_label = QtWidgets.QLabel(Dialog)
        self.postbalance_label.setGeometry(QtCore.QRect(270, 190, 101, 20))
        self.postbalance_label.setObjectName("postbalance_label")
        self.amount = QtWidgets.QTextEdit(Dialog)
        self.amount.setGeometry(QtCore.QRect(120, 170, 71, 31))
        self.amount.setObjectName("amount")
        self.fee = QtWidgets.QTextEdit(Dialog)
        self.fee.setGeometry(QtCore.QRect(120, 210, 71, 31))
        self.fee.setObjectName("fee")
        self.total = QtWidgets.QLabel(Dialog)
        self.total.setGeometry(QtCore.QRect(120, 260, 66, 17))
        self.total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total.setObjectName("total")
        self.postbalance = QtWidgets.QLabel(Dialog)
        self.postbalance.setGeometry(QtCore.QRect(270, 210, 81, 20))
        self.postbalance.setAlignment(QtCore.Qt.AlignCenter)
        self.postbalance.setObjectName("postbalance")
        self.balance = QtWidgets.QLabel(Dialog)
        self.balance.setGeometry(QtCore.QRect(290, 40, 66, 17))
        self.balance.setAlignment(QtCore.Qt.AlignCenter)
        self.balance.setObjectName("balance")
        self.address = QtWidgets.QTextEdit(Dialog)
        self.address.setGeometry(QtCore.QRect(90, 70, 291, 31))
        self.address.setObjectName("address")
        self.note = QtWidgets.QTextEdit(Dialog)
        self.note.setGeometry(QtCore.QRect(90, 110, 291, 31))
        self.note.setObjectName("note")
        self.send = QtWidgets.QPushButton(Dialog)
        self.send.setGeometry(QtCore.QRect(317, 270, 81, 27))
        self.send.setObjectName("send")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(230, 270, 81, 27))
        self.cancel.setObjectName("cancel")
        self.path_label = QtWidgets.QLabel(Dialog)
        self.path_label.setGeometry(QtCore.QRect(40, 20, 66, 17))
        self.path_label.setObjectName("path_label")
        self.path = QtWidgets.QLabel(Dialog)
        self.path.setGeometry(QtCore.QRect(40, 40, 201, 17))
        self.path.setObjectName("path")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.balance_label.setText(_translate("Dialog", "Balance"))
        self.fee_label.setText(_translate("Dialog", "Fee"))
        self.amount_label.setText(_translate("Dialog", "Amount"))
        self.total_label.setText(_translate("Dialog", "Total"))
        self.address_label.setText(_translate("Dialog", "Address"))
        self.note_label.setText(_translate("Dialog", "Note"))
        self.postbalance_label.setText(_translate("Dialog", "Balance After"))
        self.total.setText(_translate("Dialog", "0"))
        self.postbalance.setText(_translate("Dialog", "0"))
        self.balance.setText(_translate("Dialog", "0"))
        self.send.setText(_translate("Dialog", "Send"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.path_label.setText(_translate("Dialog", "Path"))
        self.path.setText(_translate("Dialog", "Bitcoin/Mohammed/key1"))

