all: bip44_page.py rcv_page.py send_page.py chain_creation.py coin_selection.py account_creation.py

bip44_page.py : bip44_page.ui
	pyuic5 bip44_page.ui -o bip44_page.py
rcv_page.py : rcv_page.ui
	pyuic5 rcv_page.ui -o rcv_page.py
send_page.py : send_page.ui
	pyuic5 send_page.ui -o send_page.py
chain_creation.py : chain_creation.ui
	pyuic5 chain_creation.ui -o chain_creation.py
coin_selection.py : coin_selection.ui
	pyuic5 coin_selection.ui -o coin_selection.py
account_creation.py : account_creation.ui
	pyuic5 account_creation.ui -o account_creation.py
