all: bip44_page.py rcv_page.py send_page.py

bip44_page.py : bip44_page.ui
	pyuic5 bip44_page.ui -o bip44_page.py
rcv_page.py : rcv_page.ui
	pyuic5 rcv_page.ui -o rcv_page.py
send_page.py : send_page.ui
	pyuic5 send_page.ui -o send_page.py


